---
- hosts: all
  become: yes
  tasks:

  - name: "Ensure that required packages are updated."
    yum:
      name: "*"
      state: latest

  - name: "Ensure that vim editor is installed."
    yum: 
      name: vim
      state: present

  - name: "Ensure that ipconfig is installed."
    yum:
      name: net-tools
      state: present

  - name: "Change ssh config"
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: PasswordAuthentication yes

  - name: 
    debug:
      msg: "{{ ansible_facts.all_ipv4_addresses }}"

  - name: "Restart sshd"
    service:
      name: sshd
      state: restarted
...