---
# tasks file for nginx
- name: "Ensure that nginx is installed."
  apt: 
    name:
      - nginx
    state: present
  when: ansible_facts['os_family']  == "Ubuntu"  

- name: "Ensure that nginx is installed."
  yum: 
    name:
      - nginx
    state: present
  when: ansible_facts['os_family']  == "RedHat"

- name: "Add Index page."
  template:
    src: "index.html.j2"
    dest: "/usr/share/nginx/html/index.html"
    owner: root
    group: root
    mode: 0755
  notify: "Restart nginx"

- name: "Wait for port {{ port }} to become open on the host, don't start checking for 10 seconds"
  wait_for:
    port: "{{ port }}"
    delay: 5

- name: "Say Hello"
  tags:
  - test
  debug:
    msg: "Hello, {{ name }}!"


- name: "Show current ip"
  debug:
    msg: "http://{{ ansible_facts.all_ipv4_addresses[0] }}:{{ port }}"
