---
- name: "Ensure that nginx is installed."
  yum: 
    name:
      - nginx
    state: latest

- name: "Show current ip"
  debug:
    msg: "{{ ansible_facts.all_ipv4_addresses[1] }}"

- name: "Start nginx"
  service:
    name: nginx
    state: started
    enabled: yes

- name: "Wait for port 80 to become open on the host, don't start checking for 10 seconds"
  wait_for:
    port: 80
    delay: 10