all:
  children:
    webservers:
      children:
        nginx:
          hosts:
            192.168.2.23:
              ansible_ssh_user: vagrant
              ansible_ssh_pass: vagrant
        caddy:
          hosts:
            192.168.2.26:
              ansible_ssh_user: vagrant
              ansible_ssh_pass: vagrant
    dbservers:
      hosts:
        10.25.1.56:
        10.25.1.57:
    mac:
      hosts:
        localhost:
          ansible_connection: local
