---
- name: "Install packages"
  hosts: webservers
  become: true
  gather_facts: false
  tags:
    - init
  tasks:

  - name: "Ensure that required packages are installed."
    yum:
      name:
        - vim
        - mc
        - epel-release
        - ca-certificates
      state: present

- name: "Install nginx"
  hosts: nginx
  become: yes
  gather_facts: true
  tags:
    - install_nginx
  roles:
    - nginx
  vars:
    username: "Netology"

- name: "Install httpd"
  hosts: httpd
  become: yes
  tags:
    - install_httpd
  roles:
    - httpd


