---
- name: "Install packages"
  hosts: webservers
  become: yes
  tags:
  - init
  tasks:

  - name: "Ensure that required packages are installed"
    yum:
      name:
        - vim
        - mc
        - epel-release
        - ca-certificates
      state: present

- name: "Install Nginx"
  hosts: nginx
  gather_facts: yes
  tags:
  - nginx
  become: true
  roles:
  - name: nginx
    vars:
    - name: "Igor"
  vars:
    name: "Playbook"

- name: "Install Caddy"
  hosts: caddy
  gather_facts: yes
  tags:
  - caddy
  become: yes
  roles:
    - role: caddy_ansible
      caddy_config: |
        https://192.168.2.26
        encode gzip
        file_server browse {
            root /home/caddy/
        }

# - name: "Install Nginx"
#   hosts: nginx
#   become: true
#   tags:
#   - nginx
#   - everything
#   gather_facts: true
#   roles:
#   - name: nginx
#     vars:
#     - name: "Igor"

# - hosts: caddy
#   become: yes
#   roles:
#     - role: caddy_ansible
#       caddy_config: |
#         https://192.168.2.25
#         encode gzip
#         file_server browse {
#             root /home/caddy/
#         }


